@startuml
!if (%not(%variable_exists("$FONTNAME")))
!$FONTNAME = "Open Sans"
!endif

!if (%not(%variable_exists("$FONTSIZE")))
!$FONTSIZE = 20
!endif


!ifdef TESTNETDARK
!$ACCENTLIGHT = "cac5f5"
!$ACCENT = "747fe4"
!$ACCENTDARK = "6631a0"
!$PRIMARY = "eae9eb"
!$SECONDARY = "333"
!$ARROWCOLOR = $ACCENT
!$ARROWFONTCOLOR = $ACCENT
!$BORDERCOLOR = $ACCENTDARK
!$BACKGROUNDCOLOR = "211b30"
!$BOXBG = $ACCENTDARK
!$DBBGCOLOR = $ACCENTDARK
!$DBFONTC = $PRIMARY
!$RECFONTC = $PRIMARY
!$RECBGCOLOR = $ACCENTDARK
!$DBBORCOLOR = $ACCENT
!$RECBORCOLOR = $ACCENT
!$LIFELINECOLOR = $ACCENTDARK
!$SEQFONTCOLOR = $ACCENTDARK
!$STEREOTYPEFONTNAME = $FONTNAME
!$ACTORBORCOLOR = $ACCENTDARK
skinparam stereotypeCBackgroundColor $ACCENTDARK
skinparam backgroundColor $BACKGROUNDCOLOR
skinparam shadowing false
skinparam roundCorner 25
skinparam defaultTextAlignment center
!endif


!ifdef TESTNETLIGHT
!$ACCENTLIGHT = "cac5f5"
!$ACCENT = "747fe4"
!$ACCENTDARK = "6631a0"
!$PRIMARY = "333"
!$SECONDARY = "eae9eb"
!$ARROWCOLOR = $ACCENT
!$ARROWFONTCOLOR = $ACCENT
!$BORDERCOLOR = $ACCENTDARK
!$BACKGROUNDCOLOR = "eae9eb"
!$BOXBG = $ACCENTDARK
!$DBBGCOLOR = $SECONDARY
!$DBFONTCOLOR = $ACCENTDARK
!$RECFONTC = $ACCENTDARK
!$RECBGCOLOR = $SECONDARY
!$RECBORCOLOR = $PRIMARY
!$DBBORCOLOR = $PRIMARY
!$LIFELINECOLOR = $ACCENTDARK
!$SEQFONTCOLOR = $ACCENTDARK
!$STEREOTYPEFONTNAME = $ACCENTDARK
!$ACTORBORCOLOR = $ACCENTDARK
skinparam stereotypeCBackgroundColor ACCENTDARK
skinparam backgroundColor BACKGROUNDCOLOR
skinparam shadowing false
skinparam roundCorner 25
skinparam defaultTextAlignment center
!endif

!ifdef IOHKDARK
!$ACCENTLIGHT = "f69ab2"
!$ACCENT = "ff3157"
!$ACCENTDARK = "333333"
!$PRIMARY = "eae9eb"
!$SECONDARY = "333"
!$BACKGROUNDCOLOR = $SECONDARY
!$ARROWCOLOR = $PRIMARY
!$ARROWFONTCOLOR = $ACCENTDARK
!$BORDERCOLOR = $ACCENTDARK
!$BOXBG ACCENTDARK 
!$DBBORCOLOR = $ACCENT
!$DBBGCOLOR = $PRIMARY
!$DBFONTCOLOR = $ACCENT
!$RECFONTC = $ACCENT
!$RECBGCOLOR PRIMARY 
!$RECBORCOLOR = $ACCENT
!$LIFELINECOLOR = $ACCENT
!$SEQFONTCOLOR = $ACCENT
!$STEREOTYPEFONTNAME = $ACCENT
!$ACTORBORCOLOR = $ACCENT
skinparam stereotypeCBackgroundColor ACCENTDARK
skinparam backgroundColor BACKGROUNDCOLOR
skinparam shadowing false
skinparam roundCorner 25
skinparam defaultTextAlignment center
!endif

!ifdef IOHKLIGHT
!$ACCENTLIGHT = "f69ab2"
!$ACCENT = "ff3157"
!$ACCENTDARK = "333333"
!$PRIMARY = "333"
!$SECONDARY = "eae9eb"
!$BACKGROUNDCOLOR = $SECONDARY
!$ARROWCOLOR = $ACCENTDARK
!$ARROWFONTCOLOR = $ACCENTDARK
!$BORDERCOLOR = $ACCENTDARK
!$BOXBG ACCENTDARK 
!$DBBORCOLOR = $ACCENT
!$DBBGCOLOR = $PRIMARY
!$DBFONTCOLOR = $ACCENT
!$RECFONTC = $ACCENT
!$RECBGCOLOR ACCENTDARK 
!$RECBORCOLOR = $ACCENT
!$LIFELINECOLOR = $ACCENT
!$SEQFONTCOLOR = $PRIMARY
!$STEREOTYPEFONTNAME = $ACCENT
!$ACTORBORCOLOR = $ACCENTDARK
skinparam stereotypeCBackgroundColor ACCENTDARK
skinparam backgroundColor BACKGROUNDCOLOR
skinparam shadowing false
skinparam roundCorner 25
skinparam defaultTextAlignment center
!endif

!procedure font_style()
  fontColor $PRIMARY
  fontName $FONTNAME
  fontSize $FONTSIZE
  stereotypeFontColor $ACCENTDARK
  stereotypeFontSize $FONTSIZE
  fontStyle lighter
!endfunction

!procedure basic_style()
  backgroundColor $BOXBG
  borderColor $BORDERCOLOR
!endfunction

!procedure accent_style()
  backgroundColor $ACCENT
  borderColor $ACCENTDARK
!endfunction

!procedure arrow_style()
  arrowColor $ARROWCOLOR
  arrowFontName $FONTNAME
  arrowFontColor $PRIMARY
  arrowFontSize $FONTSIZE
  ArrowThickness 3
  LollipopColor $ARROWCOLOR
!endfunction

skinparam title{
  FontColor $ACCENT
  FontName $FONTNAME
}

' Class diagrams

skinparam circledCharacter {
  radius 8
  fontSize $FONTSIZE
  fontName $FONTNAME
}

skinparam class {
  basic_style()
  font_style()
  arrow_style()
  attributeFontColor $SECONDARY
  attributeFontSize $FONTSIZE
  attributeIconSize $FONTSIZE
}

' Sequence diagrams
skinparam actor {
  accent_style()
  font_style()
  StereotypeFontName $STEREOTYPEFONTNAME
  fontcolor $SEQFONTCOLOR 
  borderColor  $ACTORBORCOLOR 

  
}

skinparam participant {
  basic_style()
  font_style()
  BackgroundColor $BACKGROUNDCOLOR
  BorderColor $BACKGROUNDCOLOR
  Fontcolor $SEQFONTCOLOR 
}

' Component diagrams

skinparam interface {
  accent_style()
  font_style()
}

skinparam component {
  basic_style()
  font_style()
  'StereotypeFontColor $PRIMARY
  BorderColor $ACCENT
  BackgroundColor $PRIMARY
  fontColor $SECONDARY
  stereotypeFontColor $SECONDARY
  BorderThickness 5
}

skinparam node {
  basic_style()
  font_style()
  BorderColor $ACCENT
  BackgroundColor $BACKGROUNDCOLOR
  FontName $FONTNAME
}

skinparam database {
  basic_style()
  font_style()
  BackgroundColor $DBBGCOLOR
  BorderColor $DBBORCOLOR
  StereotypeFontName $FONTNAME
  stereotypeFontColor $DBFONTCOLOR
  FontColor $DBFONTCOLOR
}

skinparam queue {
  basic_style()
  font_style()
}

'Use Case diagrams

skinparam usecase {
  basic_style()
  font_style()
  arrow_style()
}

skinparam activity {
  basic_style()
  font_style()
  arrow_style()
}

skinparam sequence {
  font_style()
  arrow_style()
  lifeLineBorderColor $LIFELINECOLOR
  LifeLineBorderThickness 3
  lifeLineBackgroundColor $ACCENT
  DividerBorderColor $ACCENT
  DividerBorderThickness 5
  DividerFontName $FONTNAME
  DividerFontStyle light
  DividerFontSize $FONTSIZE
  DividerBackgroundColor $ACCENT
  DividerFontColor $PRIMARY
  TitleFontColor $ACCENT
  TitleFontSize $FONTSIZE
  TitleFontName $FONTNAME
  StereotypeFontColor $STEREOTYPEFONTNAME
}

skinparam boundary {
  accent_style()
  font_style()
}

skinparam control {
  accent_style()
  font_style()
}

skinparam entity {
  accent_style()
  font_style()
}

' State diagrams

skinparam state {
  basic_style()
  font_style()
  arrow_style()
  startColor $ACCENT
  endColor $ACCENTDARK
}

' Object diagrams

skinparam object {
  basic_style()
  font_style()
  arrow_style()
}

' Common
skinparam note {
  accent_style()
  font_style()
}

skinparam cloud {
  basic_style()
  font_style()
  arrow_style()
  BackgroundColor $PRIMARY
  fontColor $SECONDARY
  stereotypeFontColor $SECONDARY
  BorderThickness 5
}

skinparam rectangle {
  StereotypeFontName $FONTNAME
  basic_style()
  font_style()
  BackgroundColor $RECBGCOLOR
  BorderColor $RECBORCOLOR
  stereotypeFontColor $RECFONTC
  FontColor $RECFONTC
}

skinparam storage {
  basic_style()
  font_style()
}

skinparam package {
  BackgroundColor $BACKGROUNDCOLOR
  borderColor $ACCENT
  BorderThickness 6
  FontColor $PRIMARY
  stereotypeFontColor $PRIMARY
  FontName $FONTNAME
}


skinparam caption{
?  FontColor $ACCENT
  FontName $FONTNAME
}

@enduml
